### PR TITLE
Start of best practices docs

### PR DESCRIPTION
**Pull request by kookster**
DO NOT MERGE - NOT DONE YET

### CODE REVIEW

**Comment by cavis** [comment]
Is 050 ready to go?  Or still in progress?

**Comment by kookster** [comment]
I merged in master, and I'm cleaning it up now a bit more.

**Comment by cavis** [comment]
Cool - I deployed my changes, even though the PHP examples are wrong.  At least until I get some more PR's/merging done over in the PHP sdk.

**Comment by kookster** [comment]
I think that is a pretty good start, but needs more detail, and I need to take up the client/query side more.
However, those improvements could be their own PR's, this is meant to start the docs on this, not finish them.

**Comment by cavis** [comment]
Sounds good to me.  Merging!

**Pull request merged**
